
// this file is automatically generated. you are highly discouraged from
// editing it manually
#include <zippylog/zippylog.hpp>

#include <zippylog/request_processor.pb.h>
#include <zippylog/message.pb.h>
#include <zippylog/zippylogd.pb.h>
#include <zippylog/protocol.pb.h>
#include <zippylog/device/streamer.pb.h>
#include <zippylog/protocol/response.pb.h>
#include <zippylog/protocol/request.pb.h>
// @@protoc_insertion_point(includes)

namespace zippylog {

    ZIPPYLOG_EXPORT void register_known_messages();
}
