// Generated by the lua-protobuf compiler
// You shouldn't edit this file manually
//
// source proto file: zippylog/zippylogd.proto

#include "zippylog/zippylogd.pb-lua.h"

#ifdef __cplusplus
extern "C" { // make sure functions treated with C naming
#endif

#include <lauxlib.h>

#ifdef __cplusplus
}
#endif

#include <string>
using ::std::string;

int lua_protobuf_zippylog_zippylogd_open(lua_State *L)
{
    const char *table = luaL_findtable(L, LUA_GLOBALSINDEX, "protobuf.zippylog.zippylogd", 1);
    if (table) {
        return luaL_error(L, "could not create parent Lua tables");
    }
    if (!lua_istable(L, -1)) {
        lua_newtable(L);
        lua_setfield(L, -2, "zippylog.zippylogd");
    }
    lua_pop(L, 1);
    luaL_Reg funcs [] = { { NULL, NULL } };
    luaL_register(L, "protobuf.zippylog.zippylogd", funcs);
    lua_protobuf_zippylog_zippylogd_BrokerStartup_open(L);
    lua_protobuf_zippylog_zippylogd_BrokerShutdown_open(L);
    lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_open(L);
    lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_open(L);
    lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_open(L);
    lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_open(L);
    return 1;
}


static const struct luaL_Reg BrokerStartup_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_BrokerStartup_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_BrokerStartup_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg BrokerStartup_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_BrokerStartup_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_BrokerStartup_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_BrokerStartup_gc},
    {"clear_id", lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_id},
    {"get_id", lua_protobuf_zippylog_zippylogd_BrokerStartup_get_id},
    {"set_id", lua_protobuf_zippylog_zippylogd_BrokerStartup_set_id},
    {"has_id", lua_protobuf_zippylog_zippylogd_BrokerStartup_has_id},
    {"clear_store_path", lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_store_path},
    {"get_store_path", lua_protobuf_zippylog_zippylogd_BrokerStartup_get_store_path},
    {"set_store_path", lua_protobuf_zippylog_zippylogd_BrokerStartup_set_store_path},
    {"has_store_path", lua_protobuf_zippylog_zippylogd_BrokerStartup_has_store_path},
    {"clear_listen_endpoints", lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_listen_endpoints},
    {"get_listen_endpoints", lua_protobuf_zippylog_zippylogd_BrokerStartup_get_listen_endpoints},
    {"set_listen_endpoints", lua_protobuf_zippylog_zippylogd_BrokerStartup_set_listen_endpoints},
    {"size_listen_endpoints", lua_protobuf_zippylog_zippylogd_BrokerStartup_size_listen_endpoints},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_BrokerStartup_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.BrokerStartup");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, BrokerStartup_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.BrokerStartup", BrokerStartup_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_BrokerStartup_pushcopy(lua_State *L, const ::zippylog::zippylogd::BrokerStartup &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerStartup(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerStartup");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_BrokerStartup_pushreference(lua_State *L, ::zippylog::zippylogd::BrokerStartup *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerStartup");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_BrokerStartup_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerStartup();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerStartup");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::BrokerStartup * msg = new ::zippylog::zippylogd::BrokerStartup();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerStartup");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerStartup_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerStartup_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerStartup_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    m->clear_id();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_get_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    string s = m->id();
    m->has_id() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_set_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_id();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_id(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_has_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    lua_pushboolean(L, m->has_id());
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_store_path(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    m->clear_store_path();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_get_store_path(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    string s = m->store_path();
    m->has_store_path() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_set_store_path(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_store_path();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_store_path(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_has_store_path(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    lua_pushboolean(L, m->has_store_path());
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_clear_listen_endpoints(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    m->clear_listen_endpoints();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_get_listen_endpoints(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    if (lua_gettop(L) != 2) {
        return luaL_error(L, "missing required numeric argument");
    }
    lua_Integer index = luaL_checkinteger(L, 2);
    if (index < 1 || index > m->listen_endpoints_size()) {
        return luaL_error(L, "index must be between 1 and current size: %d", m->listen_endpoints_size());
    }
    string s = m->listen_endpoints(index - 1);
    lua_pushlstring(L, s.c_str(), s.size());
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_set_listen_endpoints(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    if (lua_gettop(L) != 3) {
            return luaL_error(L, "required 2 arguments not passed to function");
    }
    lua_Integer index = luaL_checkinteger(L, 2);
    int current_size = m->listen_endpoints_size();
    if (index < 1 || index > current_size + 1) {
        return luaL_error(L, "index must be between 1 and %d", current_size + 1);
    }
    if (lua_isnil(L, 3)) {
        return luaL_error(L, "cannot assign nil to repeated fields (yet)");
    }
    size_t length = 0;
    const char *s = luaL_checklstring(L, 3, &length);
    if (index == current_size + 1) {
        m->add_listen_endpoints(s, length);
    }
    else {
        m->set_listen_endpoints(index-1, s, length);
    }
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerStartup_size_listen_endpoints(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerStartup");
    ::zippylog::zippylogd::BrokerStartup *m = (::zippylog::zippylogd::BrokerStartup *)mud->msg;
    int size = m->listen_endpoints_size();
    lua_pushinteger(L, size);
    return 1;
}

static const struct luaL_Reg BrokerShutdown_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_BrokerShutdown_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_BrokerShutdown_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg BrokerShutdown_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_BrokerShutdown_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_BrokerShutdown_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_BrokerShutdown_gc},
    {"clear_id", lua_protobuf_zippylog_zippylogd_BrokerShutdown_clear_id},
    {"get_id", lua_protobuf_zippylog_zippylogd_BrokerShutdown_get_id},
    {"set_id", lua_protobuf_zippylog_zippylogd_BrokerShutdown_set_id},
    {"has_id", lua_protobuf_zippylog_zippylogd_BrokerShutdown_has_id},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_BrokerShutdown_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, BrokerShutdown_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.BrokerShutdown", BrokerShutdown_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_BrokerShutdown_pushcopy(lua_State *L, const ::zippylog::zippylogd::BrokerShutdown &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerShutdown(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_BrokerShutdown_pushreference(lua_State *L, ::zippylog::zippylogd::BrokerShutdown *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_BrokerShutdown_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerShutdown();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerShutdown_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::BrokerShutdown * msg = new ::zippylog::zippylogd::BrokerShutdown();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerShutdown_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerShutdown_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerShutdown_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerShutdown_clear_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    m->clear_id();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerShutdown_get_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    string s = m->id();
    m->has_id() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerShutdown_set_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_id();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_id(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerShutdown_has_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerShutdown");
    ::zippylog::zippylogd::BrokerShutdown *m = (::zippylog::zippylogd::BrokerShutdown *)mud->msg;
    lua_pushboolean(L, m->has_id());
    return 1;
}

static const struct luaL_Reg BrokerReceiveClientMessage_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg BrokerReceiveClientMessage_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_gc},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, BrokerReceiveClientMessage_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.BrokerReceiveClientMessage", BrokerReceiveClientMessage_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_pushcopy(lua_State *L, const ::zippylog::zippylogd::BrokerReceiveClientMessage &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerReceiveClientMessage(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_pushreference(lua_State *L, ::zippylog::zippylogd::BrokerReceiveClientMessage *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerReceiveClientMessage();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::BrokerReceiveClientMessage * msg = new ::zippylog::zippylogd::BrokerReceiveClientMessage();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    ::zippylog::zippylogd::BrokerReceiveClientMessage *m = (::zippylog::zippylogd::BrokerReceiveClientMessage *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    ::zippylog::zippylogd::BrokerReceiveClientMessage *m = (::zippylog::zippylogd::BrokerReceiveClientMessage *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerReceiveClientMessage_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerReceiveClientMessage");
    ::zippylog::zippylogd::BrokerReceiveClientMessage *m = (::zippylog::zippylogd::BrokerReceiveClientMessage *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
static const struct luaL_Reg BrokerFlushOutputStreams_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg BrokerFlushOutputStreams_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_gc},
    {"clear_id", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_clear_id},
    {"get_id", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_get_id},
    {"set_id", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_set_id},
    {"has_id", lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_has_id},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, BrokerFlushOutputStreams_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.BrokerFlushOutputStreams", BrokerFlushOutputStreams_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_pushcopy(lua_State *L, const ::zippylog::zippylogd::BrokerFlushOutputStreams &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerFlushOutputStreams(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_pushreference(lua_State *L, ::zippylog::zippylogd::BrokerFlushOutputStreams *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::BrokerFlushOutputStreams();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::BrokerFlushOutputStreams * msg = new ::zippylog::zippylogd::BrokerFlushOutputStreams();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_clear_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    m->clear_id();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_get_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    string s = m->id();
    m->has_id() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_set_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_id();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_id(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_BrokerFlushOutputStreams_has_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.BrokerFlushOutputStreams");
    ::zippylog::zippylogd::BrokerFlushOutputStreams *m = (::zippylog::zippylogd::BrokerFlushOutputStreams *)mud->msg;
    lua_pushboolean(L, m->has_id());
    return 1;
}

static const struct luaL_Reg StoreWatcherStartup_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg StoreWatcherStartup_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_gc},
    {"clear_id", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_clear_id},
    {"get_id", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_get_id},
    {"set_id", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_set_id},
    {"has_id", lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_has_id},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, StoreWatcherStartup_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.StoreWatcherStartup", StoreWatcherStartup_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_pushcopy(lua_State *L, const ::zippylog::zippylogd::StoreWatcherStartup &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::StoreWatcherStartup(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_pushreference(lua_State *L, ::zippylog::zippylogd::StoreWatcherStartup *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::StoreWatcherStartup();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::StoreWatcherStartup * msg = new ::zippylog::zippylogd::StoreWatcherStartup();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_clear_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    m->clear_id();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_get_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    string s = m->id();
    m->has_id() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_set_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_id();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_id(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherStartup_has_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherStartup");
    ::zippylog::zippylogd::StoreWatcherStartup *m = (::zippylog::zippylogd::StoreWatcherStartup *)mud->msg;
    lua_pushboolean(L, m->has_id());
    return 1;
}

static const struct luaL_Reg StoreWatcherShutdown_functions [] = {
    {"new", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_new},
    {"parsefromstring", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_parsefromstring},
    {NULL, NULL}
};

static const struct luaL_Reg StoreWatcherShutdown_methods [] = {
    {"serialized", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_serialized},
    {"clear", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_clear},
    {"__gc", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_gc},
    {"clear_id", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_clear_id},
    {"get_id", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_get_id},
    {"set_id", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_set_id},
    {"has_id", lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_has_id},
    {NULL, NULL},
};

int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_open(lua_State *L)
{
    luaL_newmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_register(L, NULL, StoreWatcherShutdown_methods);
    lua_pushboolean(L, 1);
    lua_setfield(L, -1, "_isprotobuf");
    luaL_register(L, "protobuf.zippylog.zippylogd.StoreWatcherShutdown", StoreWatcherShutdown_functions);
    lua_pop(L, 1);
    return 1;
}


bool lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_pushcopy(lua_State *L, const ::zippylog::zippylogd::StoreWatcherShutdown &from)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::StoreWatcherShutdown(from);
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    lua_setmetatable(L, -2);
    return true;
}
bool lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_pushreference(lua_State *L, ::zippylog::zippylogd::StoreWatcherShutdown *msg, lua_protobuf_gc_callback f, void *data)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = false;
    ud->msg = msg;
    ud->gc_callback = f;
    ud->callback_data = data;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    lua_setmetatable(L, -2);
    return true;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_new(lua_State *L)
{
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = new ::zippylog::zippylogd::StoreWatcherShutdown();
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    lua_setmetatable(L, -2);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_parsefromstring(lua_State *L)
{
    if (lua_gettop(L) != 1) {
        return luaL_error(L, "parsefromstring() requires a string argument. none given");
    }
    size_t len;
    const char *s = luaL_checklstring(L, -1, &len);
    ::zippylog::zippylogd::StoreWatcherShutdown * msg = new ::zippylog::zippylogd::StoreWatcherShutdown();
    if (!msg->ParseFromArray((const void *)s, len)) {
        return luaL_error(L, "error deserializing message");
    }
    lua_protobuf_udata_t * ud = (lua_protobuf_udata_t *)lua_newuserdata(L, sizeof(lua_protobuf_udata_t));
    ud->lua_owns = true;
    ud->msg = msg;
    ud->gc_callback = NULL;
    ud->callback_data = NULL;
    luaL_getmetatable(L, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    lua_setmetatable(L, -2);
    return 1;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_gc(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    if (mud->lua_owns) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    if (mud->gc_callback && mud->gc_callback(m, mud->callback_data)) {
        delete mud->msg;
        mud->msg = NULL;
        return 0;
    }
    return 0;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_clear(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    m->Clear();
    return 0;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_serialized(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    string s;
    if (!m->SerializeToString(&s)) {
        return luaL_error(L, "error serializing message");
    }
    lua_pushlstring(L, s.c_str(), s.length());
    return 1;
}
int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_clear_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    m->clear_id();
    return 0;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_get_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    string s = m->id();
    m->has_id() ? lua_pushlstring(L, s.c_str(), s.size()) : lua_pushnil(L);
    return 1;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_set_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    if (lua_isnil(L, 2)) {
        m->clear_id();
        return 0;
    }
    
    if (!lua_isstring(L, 2)) return luaL_error(L, "passed value is not a string");
    size_t len;
    const char *s = lua_tolstring(L, 2, &len);
    if (!s) {
        luaL_error(L, "could not obtain string on stack. weird");
    }
    m->set_id(s, len);
    return 0;
}

int lua_protobuf_zippylog_zippylogd_StoreWatcherShutdown_has_id(lua_State *L)
{
    lua_protobuf_udata_t * mud = (lua_protobuf_udata_t *)luaL_checkudata(L, 1, "protobuf_.zippylog.zippylogd.StoreWatcherShutdown");
    ::zippylog::zippylogd::StoreWatcherShutdown *m = (::zippylog::zippylogd::StoreWatcherShutdown *)mud->msg;
    lua_pushboolean(L, m->has_id());
    return 1;
}
