# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
from zippylog.envelope import register_message
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='zippylog/protocol.proto',
  package='zippylog.protocol',
  serialized_pb='\n\x17zippylog/protocol.proto\x12\x11zippylog.protocol\"*\n\nStreamInfo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x04\"L\n\rStreamSetInfo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12-\n\x06stream\x18\x02 \x03(\x0b\x32\x1d.zippylog.protocol.StreamInfo\"P\n\nBucketInfo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x34\n\nstream_set\x18\x02 \x03(\x0b\x32 .zippylog.protocol.StreamSetInfo\":\n\tStoreInfo\x12-\n\x06\x62ucket\x18\x01 \x03(\x0b\x32\x1d.zippylog.protocol.BucketInfo\"\\\n\x16StoreChangeStreamAdded\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\nstream_set\x18\x02 \x01(\t\x12\x0e\n\x06stream\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x04\"^\n\x18StoreChangeStreamDeleted\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\nstream_set\x18\x02 \x01(\t\x12\x0e\n\x06stream\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x04\"_\n\x19StoreChangeStreamAppended\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\nstream_set\x18\x02 \x01(\t\x12\x0e\n\x06stream\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x04\"(\n\x16StoreChangeBucketAdded\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\"*\n\x18StoreChangeBucketDeleted\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\"?\n\x19StoreChangeStreamSetAdded\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\nstream_set\x18\x02 \x01(\t\"A\n\x1bStoreChangeStreamSetDeleted\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x12\n\nstream_set\x18\x02 \x01(\t')




_STREAMINFO = descriptor.Descriptor(
  name='StreamInfo',
  full_name='zippylog.protocol.StreamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='zippylog.protocol.StreamInfo.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='zippylog.protocol.StreamInfo.length', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=88,
)


_STREAMSETINFO = descriptor.Descriptor(
  name='StreamSetInfo',
  full_name='zippylog.protocol.StreamSetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='zippylog.protocol.StreamSetInfo.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='zippylog.protocol.StreamSetInfo.stream', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=166,
)


_BUCKETINFO = descriptor.Descriptor(
  name='BucketInfo',
  full_name='zippylog.protocol.BucketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='zippylog.protocol.BucketInfo.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.BucketInfo.stream_set', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=168,
  serialized_end=248,
)


_STOREINFO = descriptor.Descriptor(
  name='StoreInfo',
  full_name='zippylog.protocol.StoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreInfo.bucket', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=250,
  serialized_end=308,
)


_STORECHANGESTREAMADDED = descriptor.Descriptor(
  name='StoreChangeStreamAdded',
  full_name='zippylog.protocol.StoreChangeStreamAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeStreamAdded.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.StoreChangeStreamAdded.stream_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='zippylog.protocol.StoreChangeStreamAdded.stream', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='zippylog.protocol.StoreChangeStreamAdded.length', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=310,
  serialized_end=402,
)


_STORECHANGESTREAMDELETED = descriptor.Descriptor(
  name='StoreChangeStreamDeleted',
  full_name='zippylog.protocol.StoreChangeStreamDeleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeStreamDeleted.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.StoreChangeStreamDeleted.stream_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='zippylog.protocol.StoreChangeStreamDeleted.stream', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='zippylog.protocol.StoreChangeStreamDeleted.length', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=404,
  serialized_end=498,
)


_STORECHANGESTREAMAPPENDED = descriptor.Descriptor(
  name='StoreChangeStreamAppended',
  full_name='zippylog.protocol.StoreChangeStreamAppended',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeStreamAppended.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.StoreChangeStreamAppended.stream_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='zippylog.protocol.StoreChangeStreamAppended.stream', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='zippylog.protocol.StoreChangeStreamAppended.length', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=500,
  serialized_end=595,
)


_STORECHANGEBUCKETADDED = descriptor.Descriptor(
  name='StoreChangeBucketAdded',
  full_name='zippylog.protocol.StoreChangeBucketAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeBucketAdded.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=597,
  serialized_end=637,
)


_STORECHANGEBUCKETDELETED = descriptor.Descriptor(
  name='StoreChangeBucketDeleted',
  full_name='zippylog.protocol.StoreChangeBucketDeleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeBucketDeleted.bucket', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=639,
  serialized_end=681,
)


_STORECHANGESTREAMSETADDED = descriptor.Descriptor(
  name='StoreChangeStreamSetAdded',
  full_name='zippylog.protocol.StoreChangeStreamSetAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeStreamSetAdded.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.StoreChangeStreamSetAdded.stream_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=683,
  serialized_end=746,
)


_STORECHANGESTREAMSETDELETED = descriptor.Descriptor(
  name='StoreChangeStreamSetDeleted',
  full_name='zippylog.protocol.StoreChangeStreamSetDeleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bucket', full_name='zippylog.protocol.StoreChangeStreamSetDeleted.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream_set', full_name='zippylog.protocol.StoreChangeStreamSetDeleted.stream_set', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=748,
  serialized_end=813,
)

_STREAMSETINFO.fields_by_name['stream'].message_type = _STREAMINFO
_BUCKETINFO.fields_by_name['stream_set'].message_type = _STREAMSETINFO
_STOREINFO.fields_by_name['bucket'].message_type = _BUCKETINFO
DESCRIPTOR.message_types_by_name['StreamInfo'] = _STREAMINFO
DESCRIPTOR.message_types_by_name['StreamSetInfo'] = _STREAMSETINFO
DESCRIPTOR.message_types_by_name['BucketInfo'] = _BUCKETINFO
DESCRIPTOR.message_types_by_name['StoreInfo'] = _STOREINFO
DESCRIPTOR.message_types_by_name['StoreChangeStreamAdded'] = _STORECHANGESTREAMADDED
DESCRIPTOR.message_types_by_name['StoreChangeStreamDeleted'] = _STORECHANGESTREAMDELETED
DESCRIPTOR.message_types_by_name['StoreChangeStreamAppended'] = _STORECHANGESTREAMAPPENDED
DESCRIPTOR.message_types_by_name['StoreChangeBucketAdded'] = _STORECHANGEBUCKETADDED
DESCRIPTOR.message_types_by_name['StoreChangeBucketDeleted'] = _STORECHANGEBUCKETDELETED
DESCRIPTOR.message_types_by_name['StoreChangeStreamSetAdded'] = _STORECHANGESTREAMSETADDED
DESCRIPTOR.message_types_by_name['StoreChangeStreamSetDeleted'] = _STORECHANGESTREAMSETDELETED

class StreamInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STREAMINFO
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 32
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StreamInfo)

class StreamSetInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STREAMSETINFO
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 33
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StreamSetInfo)

class BucketInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BUCKETINFO
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 34
  # @@protoc_insertion_point(class_scope:zippylog.protocol.BucketInfo)

class StoreInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STOREINFO
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 35
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreInfo)

class StoreChangeStreamAdded(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGESTREAMADDED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 36
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeStreamAdded)

class StoreChangeStreamDeleted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGESTREAMDELETED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 37
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeStreamDeleted)

class StoreChangeStreamAppended(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGESTREAMAPPENDED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 38
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeStreamAppended)

class StoreChangeBucketAdded(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGEBUCKETADDED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 39
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeBucketAdded)

class StoreChangeBucketDeleted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGEBUCKETDELETED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 40
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeBucketDeleted)

class StoreChangeStreamSetAdded(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGESTREAMSETADDED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 41
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeStreamSetAdded)

class StoreChangeStreamSetDeleted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STORECHANGESTREAMSETDELETED
  
  ZIPPYLOG_NAMESPACE = 1
  ZIPPYLOG_ENUMERATION = 42
  # @@protoc_insertion_point(class_scope:zippylog.protocol.StoreChangeStreamSetDeleted)

register_message(1, 32, 'zippylog.protocol_pb2', 'StreamInfo')
register_message(1, 33, 'zippylog.protocol_pb2', 'StreamSetInfo')
register_message(1, 34, 'zippylog.protocol_pb2', 'BucketInfo')
register_message(1, 35, 'zippylog.protocol_pb2', 'StoreInfo')
register_message(1, 36, 'zippylog.protocol_pb2', 'StoreChangeStreamAdded')
register_message(1, 37, 'zippylog.protocol_pb2', 'StoreChangeStreamDeleted')
register_message(1, 38, 'zippylog.protocol_pb2', 'StoreChangeStreamAppended')
register_message(1, 39, 'zippylog.protocol_pb2', 'StoreChangeBucketAdded')
register_message(1, 40, 'zippylog.protocol_pb2', 'StoreChangeBucketDeleted')
register_message(1, 41, 'zippylog.protocol_pb2', 'StoreChangeStreamSetAdded')
register_message(1, 42, 'zippylog.protocol_pb2', 'StoreChangeStreamSetDeleted')
# @@protoc_insertion_point(module_scope)
